# podman build -t biome-dev:2.5.3 -f Containerfile.Biome .
# podman run -v .:/app:z biome-dev:2.5.3 biome --help

FROM node:22-alpine
RUN addgroup -g 1001 -S biomeuser && adduser -S biomeuser -u 1001
WORKDIR /app
RUN chown biomeuser:biomeuser /app
RUN npm install -g @biomejs/biome@2.5.3 && npm cache clean --force
USER biomeuser
