" Based on https://tlvince.com/vim-respect-xdg with some tweaks
" for syntax highlighting, but otherwise minimal.
" Annoyingly, git bash has no $XDG_CACHE_HOME etc, so we use $HOME/.cache etc.

" Setup: mkdir -p $HOME/.cache/vim/{undo,swap,backup} $HOME/.config/vim $HOME/.local/share
" Usage: export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
"        call vim


"   Embedded devices without config
":set nu
":set hlsearch

if empty("$XDG_CACHE_HOME")
  let $XDG_CACHE_HOME="$HOME/.cache"
endif
if empty("$XDG_CONFIG_HOME")
  let $XDG_CONFIG_HOME="$HOME/.config"
endif
if empty("$XDG_DATA_HOME")
  let $XDG_DATA_HOME="$HOME/.local/share"
endif

set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,~/,/tmp
"  " set viminfo+=$XDG_CACHE_HOME/vim/viminfo
set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
"  let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
"
"  "   Clipboard
"  set clipboard=unnamedplus " make all yanking/deleting automatically copy to system cliboard
"  " :echo has('clipboard') = 0 " no clipboard set
"
" Testing (no kitty protocol support to bind C,S,A,fn keys in combinations)
"noremap <silent> <s-c-f5> :echo 'ctrl+shift+f5'
"noremap <silent> <c-f5> :echo 'ctrl+f5'
"noremap <silent> <s-f5> :echo 'shift+f5'
"noremap <silent> <a-f5> :echo 'alt+f5'
"noremap <silent> <c-s-B> :echo 'ctrl+shift+b'
"noremap <silent> <c-+> :echo 'ctrl+shift+='
"noremap <silent> <c-=> :echo 'ctrl+='
"noremap <silent> <c-.> :echo 'ctrl+.'
"noremap <silent> <a-cr> :echo 'alt+enter'

"   Highlighting
" Setup:
" mkdir -p $HOME/.config/vim
" git clone https://github.com/ziglang/zig.vim $HOME/.config/vim/zig.vim
" :source $MYVIMRC
" if isdirectory($HOME/.config/vim/zig.vim)
"   set runtimepath^=$HOME/.config/vim/zig.vim
" endif
