# see https://docs.docker.com/reference/dockerfile/ for commands
# podman build -t node-dev:26 -f Containerfile.dev|prod .
# podman run --rm -p 8082:8082 -v .:/app:z -v /app/node_modules node-dev:26 npx ng serve

# LABEL to label metadata
# VOLUME to create mount point with specified name and marks it
# MAINTAINER to specify author of image
# ONBUILD to register advanced instructions to run later, during the next build stage
# using this image, inspectable via podman inspect
# ENV to set environment variables
# ADD to temporarily fetch some resources during build

# make intent explicit xor have helpful usage comments to feed necessary info
# error out on missing info
# for example to mandate --build-arg NUMPY_VERSION=SOME_VERSION, use
# ARG NUMPY_VERSION

# Do not use
# 1 EXPOSE PORT
# - to allow selecting different ports.
# 2 assume any non-root user or workdir exists or does not exist
# - OCI has is no semantics convention regarding anything.
#   Most important are however permissions by user, security.
# 3 Your own metadata should include WORKDIR and non-root users with
#   filepaths etc.

FROM docker.io/library/node:26-alpine
RUN addgroup -g 1001 -S nodejsuser && adduser -S nodejsuser -u 1001
WORKDIR /app
# followup steps are executed in WORKDIR /app
COPY package*.json ./

RUN npm ci && \
    npm cache clean --force && \
    chmod -R 555 node_modules

COPY --chown=nodejsuser:nodejsuser . .
USER nodejsuser
# followup steps are executed as USER nodejsuser
# until another USER like USER root is used.

# HEALTHCHECK to check if build was successful

# omit ENTRYPOINT and CMD to force explicit usage
