## bash aliases ##
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
alias ..........="cd ../../../../../../../../.."
alias ...........="cd ../../../../../../../../../.."
alias ............="cd ../../../../../../../../../../.."
alias .............="cd ../../../../../../../../../../../.."

# alias l='ls --color=auto --hyperlink=auto --group-directories-first -h'
# alias ls='ls --color=auto --hyperlink=auto --group-directories-first -h'
# alias ll='ls -lav --ignore=..'   # show long listing of all except ".."

#ccd() {
#  mkdir -p $1 && cd $1
#}

# assume: $1 contains https..dirname.git
# usage: makeWorkTree GIT_REMOTE
makeWorkTree() {
  worktreesdir=$(basename -s .git "$1")
  if test -e "$worktreesdir"; then
    echo "worktreesdir $worktreesdir already exists, skipping.."
    return
  fi
  echo "$worktreesdir"
  mkdir "$worktreesdir"
  cd "$worktreesdir"
  git clone --bare "$1" .bare
  # make sure git knows where the gitdir is
  echo "gitdir: ./.bare" > .git
  git worktree add master
  cd ..
}

# reset to branch $1 and apply last $2 commits
# success: exist code 0
# failure: revert, exit code 1
# usage: resetToBranchAndCherryPickLastCommits BRANCH COUNT_LAST_COMMITS
resetToBranchAndCherryPickLastCommits() {
  #current_branch=$(git symbolic-ref --short HEAD)
  git show-ref --quiet --branches "$1" || (echo "no branch $1"; return)
  [ "$2" -gt 0 ] 2>/dev/null || (echo "$2 <= 0 or no number"; return)
  commits=$(git log HEAD~"$2"..HEAD --reverse --format="%H")
  test -z "$commits" && (echo "empty commits"; return)
  original_head=$(git rev-parse HEAD)
  prev_head=$(git rev-parse HEAD~"$2")
  git reset --hard "$1" || return
  # must now revert on failure
  if ! git cherry-pick "$prev_head".."$original_head"; then
    echo "cherry-pick failed, reverting.."
    git cherry-pick --abort 2>/dev/null || true
    git reset --hard "$original_head"
  fi
}
