https://swcarpentry.github.io/make-novice/reference.html
-f file.mk
-n dry-run
make VERBOSE=1 or make V=1
--trace
make --debug=[b,i,j,m,v]
j: invocation of commands
b: Basic
v: verbose basic
i: implicit rules
m: debugging while remaking makefiles

Install to dir for usage
make install DESTDIR=$HOME/.local/cerberus