[bell.command]
args = ["/usr/share/sounds/freedesktop/stereo/complete.oga"]
program = "paplay"

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "Source Code Pro Semibold"
style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# [solarized-dark.bright]
# black = "#002b36"
# blue = "#839496"
# cyan = "#93a1a1"
# green = "#586e75"
# magenta = "#6c71c4"
# red = "#cb4b16"
# white = "#fdf6e3"
# yellow = "#657b83"
#
# [solarized-dark.cursor]
# cursor = "#839496"
# text = "#002b36"
#
# [solarized-dark.normal]
# black = "#073642"
# blue = "#268bd2"
# cyan = "#2aa198"
# green = "#859900"
# magenta = "#d33682"
# red = "#dc322f"
# white = "#eee8d5"
# yellow = "#b58900"
#
# [solarized-dark.primary]
# background = "#002b36"
# foreground = "#839496"

# [solarized-light.bright]
# black = "#073642"
# blue = "#839496"
# cyan = "#93a1a1"
# green = "#586e75"
# magenta = "#6c71c4"
# red = "#cb4b16"
# white = "#fdf6e3"
# yellow = "#657b83"
#
# [solarized-light.cursor]
# cursor = "#657b83"
# text = "#fdf6e3"
#
# [solarized-light.normal]
# black = "#002b36"
# blue = "#268bd2"
# cyan = "#2aa198"
# green = "#859900"
# magenta = "#d33682"
# red = "#dc322f"
# white = "#eee8d5"
# yellow = "#b58900"
#
# [solarized-light.primary]
# background = "#fdf6e3"
# foreground = "#657b83"

[window]
decorations = "none"