# use default column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
# remove parenthesis around function arguments, if possible
no_call_parentheses = true
