# cargo install stylua --features lua52
call_parentheses = "None"
collapse_simple_statement = "Always"
column_width = 180
indent_type = "Spaces"
indent_width = 2
line_endings = "Unix"
quote_style = "AutoPreferSingle"

[sort_requires]
enabled = true
# -- stylua: ignore
# -- stylua: ignore start
# -- stylua: ignore end