name: ci
on:
  pull_request:
  push:
    branches:
      - master
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
permissions:
  # Sets permission policy for `GITHUB_TOKEN`
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - name: Checkout action
        uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: master
          mirror: 'https://pkg.machengine.org/zig'
      - name: Run zig fmt
        if: matrix.os == 'ubuntu-latest'
        run: zig fmt --check .
      - name: Build and test without optional deps and without cross builds
        run: zig build -Dno_opt_deps -Dno_cross test --summary all
