name: ci

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

# not needed here https://github.com/actions/cache

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
          mirror: 'https://pkg.machengine.org/zig'

      # TODO: clean cache, if size of ~/.cache/zig > 5GB

      - run: zig env

      - name: Run Tests
        run: zig build -Dno_opt_deps -Dno_cross test --summary all
